// <auto-generated />
using System;
using Facturacion.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Facturacion.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814214305_A_CatalogosSat")]
    partial class A_CatalogosSat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.CatalogoVersion", b =>
                {
                    b.Property<string>("Catalogo")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("FechaCargaUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaPublicacion")
                        .HasColumnType("date");

                    b.Property<int>("RenglonesVigentes")
                        .HasColumnType("int");

                    b.Property<string>("RevisionCatalogo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("VersionCatalogo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Catalogo");

                    b.ToTable("CatalogoVersion", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatClaveProdServ", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ComplementoQueDebeIncluir")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("EstimuloFranjaFronteriza")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("IncluirIepsTrasladado")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("IncluirIvaTrasladado")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PalabrasSimilares")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatClaveProdServ", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatClaveUnidad", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Nota")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Simbolo")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatClaveUnidad", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatCodigoPostal", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ClaveEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ClaveLocalidad")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ClaveMunicipio")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("EstimuloFranjaFronteriza")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatCodigoPostal", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatColonia", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ClaveCodigoPostal")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<int>("IdInterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInterno"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave", "ClaveCodigoPostal");

                    b.HasIndex("ClaveCodigoPostal");

                    b.HasIndex("IdInterno")
                        .IsUnique();

                    b.ToTable("SatColonia", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatEstado", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ClavePais")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatEstado", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatExportacion", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatExportacion", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatFormaPago", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatFormaPago", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatImpuesto", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("LocalOFederal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Retencion")
                        .HasColumnType("bit");

                    b.Property<bool>("Traslado")
                        .HasColumnType("bit");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatImpuesto", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatMes", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatMes", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatMetodoPago", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatMetodoPago", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatMoneda", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Decimales")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatMoneda", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatMunicipio", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ClaveEstado")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<int>("IdInterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInterno"));

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave", "ClaveEstado");

                    b.HasIndex("IdInterno")
                        .IsUnique();

                    b.ToTable("SatMunicipio", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatObjetoImp", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatObjetoImp", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatPais", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatPais", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatPeriodicidad", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatPeriodicidad", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatRegimenFiscal", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("AplicaFisica")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaMoral")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatRegimenFiscal", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatTasaOCuota", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Factor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Impuesto")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RangoOFijo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Retencion")
                        .HasColumnType("bit");

                    b.Property<bool>("Traslado")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorMaximo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatTasaOCuota", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatTipoDeComprobante", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatTipoDeComprobante", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatTipoFactor", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatTipoFactor", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatTipoRelacion", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatTipoRelacion", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Catalogos.SatUsoCfdi", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("AplicaFisica")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaMoral")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("RegimenesFiscalesAplicables")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Clave");

                    b.ToTable("SatUsoCfdi", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.ClaveIdempotencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CodigoEstado")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashPeticion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RespuestaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraUtc");

                    b.HasIndex("EmpresaId", "Clave")
                        .IsUnique();

                    b.ToTable("ClavesIdempotencia", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoContacto")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime>("FechaAltaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.ToTable("Cuentas", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoPostalExpedicion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAltaUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LicComercio")
                        .HasColumnType("bit");

                    b.Property<bool>("LicINE")
                        .HasColumnType("bit");

                    b.Property<bool>("LicNotarios")
                        .HasColumnType("bit");

                    b.Property<bool>("LicObras")
                        .HasColumnType("bit");

                    b.Property<string>("NombreFiscal")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId", "Rfc")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Permiso", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Clave");

                    b.ToTable("Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Clave = "timbrar",
                            Descripcion = "Emitir y timbrar comprobantes"
                        },
                        new
                        {
                            Clave = "cancelar",
                            Descripcion = "Cancelar comprobantes timbrados"
                        },
                        new
                        {
                            Clave = "administrar_usuarios",
                            Descripcion = "Invitar usuarios y asignar permisos"
                        },
                        new
                        {
                            Clave = "comprar_timbres",
                            Descripcion = "Comprar paquetes de timbres"
                        },
                        new
                        {
                            Clave = "ver_reportes",
                            Descripcion = "Consultar reportes de la empresa"
                        },
                        new
                        {
                            Clave = "configurar_empresa",
                            Descripcion = "Configurar la empresa, sus series y sus certificados"
                        });
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgenteUsuario")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ConsumidoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmpresaActivaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MotivoRevocacion")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ReemplazadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevocadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("HashToken")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.RegistroBitacora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("MomentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId", "MomentoUtc");

                    b.HasIndex("EmpresaId", "MomentoUtc");

                    b.ToTable("Bitacora", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("BloqueosConsecutivos")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAltaUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemaPreferido")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.UsuarioEmpresa", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAltaUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "EmpresaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("UsuariosEmpresas", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.UsuarioEmpresaPermiso", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermisoClave")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("OtorgadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OtorgadoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "EmpresaId", "PermisoClave");

                    b.HasIndex("PermisoClave");

                    b.ToTable("UsuariosEmpresasPermisos", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Empresa", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Cuenta", "Cuenta")
                        .WithMany("Empresas")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.RefreshToken", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Usuario", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Cuenta", "Cuenta")
                        .WithMany("Usuarios")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.UsuarioEmpresa", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Usuario", "Usuario")
                        .WithMany("Empresas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.UsuarioEmpresaPermiso", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoClave")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.UsuarioEmpresa", "UsuarioEmpresa")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("UsuarioEmpresa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Facturacion.Server.Data.Entidades.Plataforma.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Cuenta", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.Usuario", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("Facturacion.Server.Data.Entidades.Plataforma.UsuarioEmpresa", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
