# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - facturacion-luis-dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore Facturacion.sln

      - name: Build solution
        run: dotnet build Facturacion.sln --configuration Release --no-restore

      - name: Publish server and client
        run: dotnet publish Facturacion.Server/Facturacion.Server.csproj --configuration Release --no-restore -o "${{ runner.temp }}\facturacion-publicada"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ runner.temp }}\facturacion-publicada

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publicacion
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5F41329EB3314C7EAAB9107258C3545D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6B97AE2A0C04D73822E6F9529253B13 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B597659A9A714FD5A2FBB2AD9AB92607 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'facturacion-luis-dev'
          slot-name: 'Production'
          package: ./publicacion
